import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <h1 className="bg-gray-600 text-blue-50 font-bold p-4 text-2xl">Next Js</h1>
         
        </div>
        {children}
        <div><h1 className="bg-green-800 text-blue-50 font-bold p-4 f-2 text-2xl">Footer</h1></div>
        
      </body>
    </html>
  );
}
